# Generated by Django 6.0.4 on 2026-04-24 14:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transport'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('health', 'Health & Medical'), ('shopping', 'Shopping'), ('education', 'Education'), ('rent', 'Rent & Housing'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['category'], name='expenses_ex_categor_fcaba7_idx'), models.Index(fields=['-date', '-created_at'], name='expenses_ex_date_840b41_idx')],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('key', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_key', to='expenses.expense')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='expenses_id_created_feef16_idx')],
            },
        ),
    ]
